services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_DB: musicbooru
      POSTGRES_USER: musicbooru
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

    volumes:
      - db:/data/postgres

    ports:
      - "5332:5432"

    networks:
      - db

    restart: unless-stopped

  app:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .

    container_name: app
    depends_on:
      - db

    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicbooru
      - SPRING_DATASOURCE_USERNAME=musicbooru
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: