#file: noinspection SpellCheckingInspection

services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_DB: musicbooru
      POSTGRES_USER: trackmaster
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped

  app:
    container_name: app
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicbooru
      - SPRING_DATASOURCE_USERNAME=trackmaster
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db: