#file: noinspection SpellCheckingInspection

services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_DB: musicbooru
      POSTGRES_USER: trackmaster
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    container_name: app
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicbooru
      - SPRING_DATASOURCE_USERNAME=trackmaster
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: