### Admin login
POST http://localhost:80/api/auth/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "1337"
}

### User login
POST http://localhost:80/api/auth/authenticate
Content-Type: application/json

{
  "username": "userguy",
  "password": "1234"
}

### Register user
POST http://localhost:80/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJBRE1JTiJdLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NjMzOTk5MywiZXhwIjoxNzU2MzQxNDMzfQ.J041Tu7t3NLildavgNg4Ywx7IhUyNkVJPs3hkgoXwvw
Content-Type: application/json

{
  "username": "userguy",
  "password": "1234"
}

### Upload track
POST http://localhost:80/api/track/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.flac"
Content-Type: audio/flac

< /path/to/file
--boundary--

### Delete track
POST http://localhost:80/api/track/delete/1

### Get tracks
GET http://localhost:80/api/track/

### Stream track
GET http://localhost:80/api/track/stream/1