spring.application.name=MusicBooru

spring.datasource.url=jdbc:postgresql://localhost:6432/musicbooru
spring.datasource.username=musicbooru
spring.datasource.password=supersecretpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

garage.endpoint=http://localhost:3900
garage.access-key=GK030f2a01e4d8627c399506a7
garage.secret-key=c3f702942bf76817ad9f7175db5cfe64521bd5263be1298011971c9334ff7873
garage.bucket-library=library
garage.bucket-artwork=artwork

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=4

logging.file.name=musicbooru.log
logging.level.com.example.musicbooru=DEBUG

app.default-admin.username=admin
app.default-admin.password=supersecretpassword