spring.application.name=MusicBooru

spring.datasource.url=jdbc:postgresql://localhost:6432/musicbooru
spring.datasource.username=musicbooru
spring.datasource.password=supersecretpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

# openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 44
jwt.secret=ZHbE8QaaFw2YqCdMwrEKrNZ1tNCZ4lR8LI6fxtNjNlYK
jwt.expiration=1440

garage.endpoint=http://localhost:3900
garage.access-key=GKedb14f061a6f3247ee4de55b
garage.secret-key=4f6b803123670faca14f91b5e152ae77a4e51d85a09ed1876cd5ea0641d312cc
garage.bucket-library=library
garage.bucket-artwork=artwork

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=4

logging.file.name=musicbooru.log
logging.level.com.example.musicbooru=DEBUG

app.default-admin.username=admin
app.default-admin.password=supersecretpassword