name: Codeberg Mirror
on:
  push:
    branches: ["**"]
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run : |
          git remote add codeberg https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/George-Markas/MusicBooru
          git push --mirror codeberg